kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privilegedpsp
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privileged
