kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gitlab
  namespace: gitlab-th2
spec:
  host: gitlab.th2.apps.okd.example.com
  to:
    kind: Service
    name: gitlab-nginx-ingress-controller
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
